### ISSUE TITLE
Python 3.6 issue with KeyError: 'request'

### ISSUE THREAD

**Issue by cdnsteve** [imanhodjaev/django-auth0#15]
Using Python 3.6.1 and Django 1.11 also tried with 1.11.1

Make sure you enable the auth backends:
```
AUTHENTICATION_BACKENDS = [
    'django_auth0.auth_backend.Auth0Backend',
    'django.contrib.auth.backends.ModelBackend'
]
```

While running tox after setting up backend
```
======================================================================
ERROR: test_login_process_returns_400 (tests.test_auth_helper.TestDjangoAuth0)
It returns HTTP 400 when profile data from Auth0 is empty
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cittzl/Dev/Github/django-auth0/.tox/py36/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 72, in authenticate
    inspect.getcallargs(backend.authenticate, request, **credentials)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 1314, in getcallargs
    (f_name, kw))
TypeError: authenticate() got multiple values for argument 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cittzl/Dev/Github/django-auth0/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/Users/cittzl/Dev/Github/django-auth0/tests/test_auth_helper.py", line 70, in test_login_process_returns_400
    result = auth_helpers.process_login(request)
  File "/Users/cittzl/Dev/Github/django-auth0/django_auth0/auth_helpers.py", line 41, in process_login
    user = authenticate(**user_info)
  File "/Users/cittzl/Dev/Github/django-auth0/.tox/py36/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
    inspect.getcallargs(backend.authenticate, request=request, **credentials)
KeyError: 'request'

----------------------------------------------------------------------
Ran 10 tests in 0.020s

FAILED (errors=1)
Destroying test database for alias 'default'..
```

**Comment by sultaniman** [comment]
@cdnsteve I will test it with Python 3.6.1 and will try to fix this.

**Comment by denself** [comment]
Looks like it is fixed in Django 1.11.4

**Comment by graup** [comment]
Thanks @cdnsteve for reporting and @denself for providing the solution, this saved me a lot of time troubleshooting!

**Comment by sultaniman** [comment]
@denself thanks for feedback. I hope soon I will be able to pick up this again and make updates which are in kind of limbo state at the moment.
